#!/bin/sh

#Convert images from original quality to various qualities to be used in this repo

# Create directories
if [[ $1 == "setup" ]]
then
   mkdir gallery gallery/thumbnail gallery/web gallery/hq import import/original import/original_small
   exit
fi

# Delete PNG originals and cleans up .git directory
if [[ $1 == "cleanup" ]]
then
   rm -rf import/original import/original_small
   mkdir import/original import/original_small
   git reflog expire --expire=now --all
   git gc --auto
   exit
fi

# Fetch PNG originals from repo
if [[ $1 == "download" ]]
then
    rm -r import
    git clone git@github.com:spacebanana420/image-gallery-originals.git
    mv image-gallery-originals import
    exit
fi

if [[ $1 == "rewrite" ]] # Rewrite all images
then
    overwrite="-y"
elif [[ $1 == "reset" ]] # Erase all images and rewrite
then
    overwrite="-y"
    rm -r gallery
    mkdir gallery gallery/thumbnail gallery/web gallery/hq
else # Only write new images
    overwrite="-n"
fi

#Create lower-quality previews for all images
for i in import/original/*.png import/original_small/*.png
do
  newname=$(basename "$i" ".png")
  ffmpeg $overwrite -i "$i" -quality 78 -filter:v "scale=500:-1" gallery/thumbnail/"$newname".webp
  ffmpeg $overwrite -i "$i" -quality 88 -filter:v "scale=950:-1" gallery/web/"$newname".webp
  
done

#For images above 1920 width, make a HQ version that is 1920 wide
for i in import/original/*.png
do
  newname=$(basename "$i" ".png")
  ffmpeg $overwrite -i "$i" -qmin 1 -q 1 -filter:v "scale=1920:-1" gallery/hq/"$newname".jpg
done

#For images equal or below 1920 width, make a HQ version without resizing instead
for i in import/original_small/*.png
do
  newname=$(basename "$i" ".png")
  ffmpeg $overwrite -i "$i" -qmin 1 -q 1 gallery/hq/"$newname".jpg
done
