#!/bin/sh

#Convert images from original quality to various qualities to be used in this repo

rm -r gallery
mkdir gallery gallery/thumbnail gallery/web gallery/hq

#Create thumbnail and high quality variants for all images
for i in import/original/*.png import/original_small/*.png
do
  newname=$(basename "$i" ".png")
  ffmpeg -y -i "$i" -quality 90 -filter:v "scale=650:-1" gallery/thumbnail/"$newname".webp
  ffmpeg -y -i "$i" -qmin 1 -q 1 gallery/hq/"$newname".jpg
done

#For images above 1920x1080, make a preview that is 1920 wide
for i in import/original/*.png
do
  newname=$(basename "$i" ".png")
  ffmpeg -y -i "$i" -quality 90 -filter:v "scale=1920:-1" gallery/web/"$newname".webp
done

#For images equal or below 1920x1080, make a preview without resizing instead
for i in import/original_small/*.png
do
  newname=$(basename "$i" ".png")
  ffmpeg -y -i "$i" -quality 90 gallery/web/"$newname".webp
done
